### PR TITLE
[release-4.6][ART-3664] Bug 2043805: IPs with leading zeros are still valid in the apiserver

### PR DESCRIPTION
**Pull request by locriandev**
ref https://issues.redhat.com/browse/ART-3664
backport of [#287](https://github.com/openshift/openshift-apiserver/pull/287)

### CODE REVIEW

**Comment by sosiouxme** [comment]
/retest
[test failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_openshift-apiserver/288/pull-ci-openshift-openshift-apiserver-release-4.6-e2e-cmd/1526562492463976448) looks unrelated

**Review by soltysh — APPROVED** [review]
/label backport-risk-assessed

**Pull request merged**
