### PR TITLE
Bug 1877363: fix missing conversions for DeploymentLogOptions

### PR DESCRIPTION
**Pull request by soltysh**
/assign @p0lyn0mial @sttts

### CODE REVIEW

**Comment by sttts** [comment]
/hold

How did we pass CI without this?

**Comment by p0lyn0mial** [comment]
> How did we pass CI without this?

Are we missing an e2e test ?

**Comment by p0lyn0mial** [comment]
> Are we missing an e2e test ?

Could be, it will only occur when you do `oc logs -f dc/deployment`, right ?

**Comment by sttts** [comment]
Please make sure we have a test.

**Comment by soltysh** [comment]
> Please make sure we have a test.

Yeah, on my list.

**Pull request merged**
