### PR TITLE
Bug 1905195: Detecting broken connections to the Kube API takes up to 15 minutes

### PR DESCRIPTION
**Pull request by p0lyn0mial**
we will carry a patch that allows the client to detect broken connections to the api server more quickly than the default TCP timeout of 15 minutes.

this patch will be dropped in future releases once http2/ping is introduced.

ref: https://github.com/openshift/library-go/pull/945

### CODE REVIEW

**Comment by rhpmali** [comment]
As per pre-merge verification. The bug is pre-merge verified in https://bugzilla.redhat.com/show_bug.cgi?id=1905195#c3 , adding QE lgtm:
/lgtm

**Comment by crawford** [comment]
Cherry-pick-approved removed. Tests are too flaky and we already have too many fixes to be verified this cycle.

**Comment by soltysh** [comment]
e2e-cmd is known to be flakey and it's currently awaiting openshift/origin#25831

**Comment by mfojtik** [comment]
/override ci/prow/e2e-cmd

This is known broken and the fix just merged.

**Pull request merged**
