### PR TITLE
Add allow host users

### PR DESCRIPTION
**Pull request by haircommander**
Carrying a bunch, using this to test in a cluster

### CODE REVIEW

**Review by ibihim — COMMENTED** [review]
/lgtm

**Comment by benluddy** [comment]
I was under the impression that SCC is served by kube-apiserver via CRD on all flavors these days (https://github.com/openshift/kubernetes/blob/a3f31a4f2c587420f1ddb3bcdb161bf64a8c436b/openshift-kube-apiserver/enablement/intialization.go#L63). Do we have a reason to keep maintaining this?

**Comment by haircommander** [comment]
yeah it seems we actually don't need this after all...

/close

**Pull request closed without merging**
