### PR TITLE
OCPBUGS-31666: Bump openshift/api for Route API godoc fix

### PR DESCRIPTION
**Pull request by Miciah**
Bump to https://github.com/openshift/api/commit/8203151f085f2205ba7fa64f093a04a742d1cb87, which fixes the godoc for the `Route.spec.tls.insecureEdgeTerminationPolicy` field to say that "None", not "Allow", is the default value.  

Bump to https://github.com/openshift/library-go/commit/cb8aac942b79e973d2c37168ccff36c882200856 to fix build errors in library-go resulting from changes in openshift/api.  

Update `NewOpenshiftAPIConfig` likewise to read feature definitions from their new location in openshift/api.

Follow-up to https://github.com/openshift/api/pull/1845.

### CODE REVIEW

**Comment by Miciah** [comment]
https://github.com/openshift/openshift-apiserver/compare/4b0a7a5ef1bcdcb7dfc6fed1f89b0632ecd11d96..f15a6b96f2cf13e83ac665f3c644e51b36be2744 bumps the vendored library-go to fix build errors that resulted from the openshift/api bump.

**Comment by Miciah** [comment]
https://github.com/openshift/openshift-apiserver/compare/f15a6b96f2cf13e83ac665f3c644e51b36be2744..b3335a8d02a3cc20d95dbd908e59b209872b98d7 fixes one more build error resulting from the openshift/api bump.

**Comment by Miciah** [comment]
https://github.com/openshift/openshift-apiserver/compare/b3335a8d02a3cc20d95dbd908e59b209872b98d7..b983b70ed06cf64f18cd5420f963f315d120fe6a fixes some more build failures from the openshift/api bump.

**Comment by ShudiLi** [comment]
tested it with 4.16.0-0.ci.test-2024-05-08-031552-ci-ln-hmrbdf2-latest:  If a route does not specify insecureEdgeTerminationPolicy, then the default behavior is "None".

```
1.
% oc get clusterversion   
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.16.0-0.ci.test-2024-05-08-031552-ci-ln-hmrbdf2-latest   True        False         6m17s   Cluster version is 4.16.0-0.ci.test-2024-05-08-031552-ci-ln-hmrbdf2-latest
% 

2.
% oc explain routes.spec.tls.insecureEdgeTerminationPolicy
GROUP:      route.openshift.io
KIND:       Route
VERSION:    v1

FIELD: insecureEdgeTerminationPolicy <string>

DESCRIPTION:
    insecureEdgeTerminationPolicy indicates the desired behavior for insecure
    connections to a route. While each router may make its own decisions on
    which ports to expose, this is normally port 80.
    
    If a route does not specify insecureEdgeTerminationPolicy, then the default
    behavior is "None".
    
    * Allow - traffic is sent to the server on the insecure port (edge/reencrypt
    terminations only).
    
    * None - no traffic is allowed on the insecure port (default).
    
    * Redirect - clients are redirected to the secure port.
    

%
```

**Comment by ShudiLi** [comment]
/label qe-approved
thanks

**Pull request merged**
