### PR TITLE
Bug 1957584: Revert 'Bug 1896977: Enhance API host name validation'

### PR DESCRIPTION
**Pull request by Miciah**
This reverts commit 402c0fdc3b10abfef4d3b4fbc09e14e33a0a8dbf.

### CODE REVIEW

**Comment by quarterpin** [comment]
/lgtm
/label qe-approved

Verified via pre-merge verification workflow, more reference related to the test can be found in:
https://bugzilla.redhat.com/show_bug.cgi?id=1957584#c15

**Comment by Miciah** [comment]
STEP 2: ENV "BUILD_LOGLEVEL"="0" "CLONEREFS_OPTIONS"="{\"src_root\":\"/go\",\"log\":\"/dev/null\",\"git_user_name\":\"ci-robot\",\"git_user_email\":\"ci-robot@openshift.io\",\"refs\":[{\"org\":\"openshift\",\"repo\":\"openshift-apiserver\",\"repo_link\":\"https://github.com/openshift/openshift-apiserver\",\"base_ref\":\"master\",\"base_sha\":\"aab4989f7957923355205378660f65a2bb0dd71d\",\"base_link\":\"https://github.com/openshift/openshift-apiserver/commit/aab4989f7957923355205378660f65a2bb0dd71d\",\"pulls\":[{\"number\":210,\"author\":\"Miciah\",\"sha\":\"caa8773bf4976b7311496e190b0d237675db12b7\",\"title\":\"Bug 1957584: Revert \\\"Bug 1896977: Enhance API host name validation\\\"\",\"link\":\"https://github.com/openshift/openshift-apiserver/pull/210\",\"commit_link\":\"https://github.com/openshift/openshift-apiserver/pull/210/commits/caa8773bf4976b7311496e190b0d237675db12b7\",\"author_link\":\"https://github.com/Miciah\"}]}],\"fail\":true}"
    STEP 3: ADD ./clonerefs /clonerefs
    STEP 4: RUN umask 0002 && /clonerefs && find /go/src -type d -not -perm -0775 | xargs --max-procs 10 --max-args 100 --no-run-if-empty chmod g+xw
    time="2021-05-27T04:49:52Z" level=warning msg="Path \"/run/secrets/etc-pki-entitlement\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
    time="2021-05-27T04:49:52Z" level=warning msg="Path \"/run/secrets/redhat.repo\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
    {"component":"clonerefs","file":"prow/cmd/clonerefs/main.go:32","func":"main.main","level":"fatal","msg":"Could not resolve options: could not load config from JSON var CLONEREFS_OPTIONS: invalid character 'B' after object key:value pair","severity":"fatal","time":"2021-05-27T04:49:53Z"}

/retitle Bug 1957584: Revert 'Bug 1896977: Enhance API host name validation'
/test e2e-aws-serial

**Pull request merged**
