### PR TITLE
Use github.com/openshift/runtime-utils/pkg/registries

### LINKED ISSUE #41: Use openshift/runtime-utils/pkg/registries and containers/image instead local copies
#23 has added private copies of:
- `pkg/image/apiserver/registries` (at the time from `openshift/machine-config-operator`) now available in `openshift-runtime-utils/pkg/registries`)
- <s>`pkg/image/apiserver/sysregistriesv2` (from `containers/image/pkg/sysregistriesv2`)</s>

It would be nice to instead vendor the upstream code, so that we can use all the existing vendoring tools to recognize/manage outdated dependencies and their updates.

(OTOH, it would drag in a few more not really used dependencies: https://github.com/openshift/openshift-apiserver/pull/23#discussion_r327776923 https://github.com/openshift/openshift-apiserver/pull/23#discussion_r327833691 .)

### PR DESCRIPTION
**Pull request by mtrmac**
... instead of a local copy.

<s>The code is currently 100% identical, so this doesn't make a difference, but that will change with https://github.com/openshift/runtime-utils/pull/11 . </s>

Fixes #41 .

### CODE REVIEW

**Comment by mtrmac** [comment]
@umohnani8 FYI. The wildcard support will also require changes to `pkg/image/apiserver/importer.ImageStreamImporter` .

**Comment by umohnani8** [comment]
@mtrmac do I need to wait for this PR to get n before making the changes suggested above in https://github.com/openshift/openshift-apiserver/pull/205#issuecomment-827140024?

**Comment by mtrmac** [comment]
> @mtrmac do I need to wait for this PR to get in before making the changes suggested above in [#205 (comment)](https://github.com/openshift/openshift-apiserver/pull/205#issuecomment-827140024)?

@umohnani8 It would be a start, but it needs to be followed by updating to a version that supports wildcards; only then can `ImageStreamImporter` be extended to read wildcard configuration. So, alternatively, it would be possible to skip this code-move-only PR and directly vendor a version with wildcards.

**Comment by mtrmac** [comment]
Almost a year later… @QiWang19 this is one of the repos that should eventually be updated for https://github.com/openshift/enhancements/pull/929 .

**Comment by mtrmac** [comment]
I have rebased the original ~do-nothing commit, and added one that updates to the current version of runtime-utils. Note that there is some code that interprets the config directly, e.g. in `pkg/image/apiserver/importer/importer.go` and that looks obsolete/broken with the new semantics. So more work would be necessary to fully support non-registry scopes.

**Comment by umohnani8** [comment]
/remove-lifecycle rotten
@mtrmac is there anything that is blocking this from getting in?

**Comment by mtrmac** [comment]
@umohnani8 I don’t know. I keep rebasing this and… crickets. At this point I’m basically resigned to the bot closing it.

**Comment by umohnani8** [comment]
Changes LGTM
@sttts @adambkaplan PTAL

**Comment by umohnani8** [comment]
@deads2k @mfojtik @sttts PTAL

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
