### PR TITLE
[release-4.7][ART-3664] Bug 2043804: IPs with leading zeros are still valid in the apiserver

### PR DESCRIPTION
**Pull request by sosiouxme**
backport of https://github.com/openshift/openshift-apiserver/pull/280
ref https://issues.redhat.com/browse/ART-3664

### CODE REVIEW

**Comment by zxiao-redhat** [comment]
Launched one 4.7 cluster with this PR successfully, verification steps see [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2043804)

**Comment by sosiouxme** [comment]
@sttts approve this backport?

**Comment by sttts** [comment]
No test?

**Pull request merged**
