### PR TITLE
Remove SCC bootstrap from post startup hooks

### PR DESCRIPTION
**Pull request by tkashem**
Disable default SCC bootstrap by removing `bootstrapSCC` from post startup hooks.

The default SCC are being bootstrapped by `kube-apiserver-operator`, so we don't need to bootstrap these from `openshift-apiserver` any longer. 

Related PRs
* https://github.com/openshift/cluster-version-operator/pull/308
* https://github.com/openshift/cluster-kube-apiserver-operator/pull/725

### CODE REVIEW

**Comment by tkashem** [comment]
Holding it, until qe validates that the default SCC are being bootstrapped by `kube-apiserver-operator`

/hold

**Comment by tkashem** [comment]
qe verification complete

/hold cancel

**Comment by deads2k** [comment]
remove the code https://github.com/openshift/openshift-apiserver/pull/78

**Comment by tkashem** [comment]
> remove the code #78

@deads2k can you take a look? I removed the function and the test artifacts.

**Comment by tkashem** [comment]
closing it, https://github.com/openshift/openshift-apiserver/pull/78 already merged, they are identical.

**Pull request closed without merging**
