### PR TITLE
WIP: Bug 1876500: update buildconfig generator logic to use status imagechangetriggers

### PR DESCRIPTION
**Pull request by gabemontero**
has place holder API update commit until openshift/api#744 is merged, then this PR will vendor in that change, and the place holder commit will be removed from this PR

/assign @adambkaplan

### CODE REVIEW

**Comment by gabemontero** [comment]
The unit test / verify failures are related to my hacking in the openshift/api changes and not being able to run `make update` cleanly (I can run it cleanly on master branch).

The unit tests I updated as part of this passed.

The failed unit test is:

```
FAIL: github.com/openshift/openshift-apiserver/pkg/api TestRoundTripTypes 18.14s
```

**Comment by gabemontero** [comment]
yep ... as noted in the OCM PR https://github.com/openshift/openshift-controller-manager/pull/136#issuecomment-696931458 the ICT tests fail in apiserver e2e-aws as well, without the corresponding OCM changes

Probably API / behavior like this has not changed since we split out OCM from the apiserver back in the early 4.x days @adambkaplan ... back when we would iterate on this in 3.x it was all in openshif/origin

So we'll have to get creative with how we stage across the 2 repos.

First thing that comes to mind is update *BOTH* spec and status in both repos, then remove the updating of spec subequent PRs in both repos.

Discussion fodder for tomorrow's scrum.

**Comment by gabemontero** [comment]
unit test failure still on `FAIL: github.com/openshift/openshift-apiserver/pkg/api TestRoundTripTypes 20.38s` per https://github.com/openshift/openshift-apiserver/pull/138#issuecomment-696953030

**Comment by gabemontero** [comment]
And to go along with https://github.com/openshift/openshift-controller-manager/pull/136#issuecomment-697856211 @adambkaplan  the ict tests are passing in e2e-aws with  https://github.com/openshift/openshift-apiserver/pull/138/commits/7237fa0d63e1fc8acd3d14ed182ead4f77b02b41 where we leave the unit tests as is for verifying the status LastTriggeredImageID is set, but the code sets both spec and status to facilitate an OCM without https://github.com/openshift/openshift-controller-manager/pull/136

we merge https://github.com/openshift/api/pull/744 when 4.7 opens up; vendor here, merge this PR, and then when both PRs merge, we create a subsequent PR that removes https://github.com/openshift/openshift-apiserver/pull/138/commits/7237fa0d63e1fc8acd3d14ed182ead4f77b02b41

**Comment by adambkaplan** [comment]
/hold

Per discussion with @bparees, altering the behavior of how the `lastTriggeredImageID` is set can have unintended consequences.

**Comment by gabemontero** [comment]
/close

between @pweil- @bparees @adambkaplan and myself we've concluded removal of this from spec could break existing users who built on the current behavior

@adambkaplan is driving mitigations with customer ... based on fallout, if some altered form of this is taken on, we'll go from there

**Pull request closed without merging**
