### PR TITLE
Bug 1894916:  Panic output due to timeouts in openshift-apiserver

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by xingxingxia** [comment]
Pre-merge test passes in [1894916#c4](https://bugzilla.redhat.com/show_bug.cgi?id=1894916#c4), so adding QE lgtm:
/lgtm

**Comment by soltysh** [comment]
e2e-cmd is known to be flakey and it's currently awaiting https://github.com/openshift/origin/pull/25831 

/override ci/prow/e2e-cmd

**Comment by mfojtik** [comment]
/override ci/prow/e2e-cmd

This is known broken and being fixed already in origin PR.

**Pull request merged**
