### PR TITLE
NO-JIRA: apiserver: sanitize the generic config for the chained servers

### PR DESCRIPTION
**Pull request by p0lyn0mial**
alternative to https://github.com/openshift/kubernetes-apiserver/pull/59

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold 

needs an e2e test

**Comment by p0lyn0mial** [comment]
@dinhxuanvu once the CI is green on this PR please test is instead of https://github.com/openshift/kubernetes-apiserver/pull/59

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by p0lyn0mial** [comment]
https://github.com/openshift/origin/pull/29148 merged

/test all

**Comment by p0lyn0mial** [comment]
` [sig-api-machinery] API health endpoints should contain the required checks for the openshift-apiserver APIs [Suite:openshift/conformance/parallel]` is green in https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_openshift-apiserver/452/pull-ci-openshift-openshift-apiserver-master-e2e-aws-ovn/1841840740607463424

/hold cancel

**Pull request merged**
