### PR TITLE
Bug 2026380: Image policy should mutate DeploymentConfigs

### PR DESCRIPTION
**Pull request by dmage**
This is a backport of #261 to address the [bug 2026380](https://bugzilla.redhat.com/show_bug.cgi?id=2026380).

**Impact:** Resolution of image stream names in deployment configs does not work because the image policy plugin does not know about them.

**Cause:** The problem exists since the beginning, but it wasn't visible as the image policy plugin used to resolve image streams names in all pods. Once we've fixed the [bug 1925180](https://bugzilla.redhat.com/show_bug.cgi?id=1925180), the plugin doesn't update controlled objects anymore, i.e. it doesn't update pods that are created for the deployment config.

**Resolution:** Update the admission plugin so that is aware of deployment configs.

### CODE REVIEW

**Comment by dmage** [comment]
It seems failures are not related to the this PR.
/retest

**Comment by dmage** [comment]
```
docker.io/library/nginx:latest: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
we may want to backport https://bugzilla.redhat.com/show_bug.cgi?id=1904684 to 4.6

**Comment by soltysh** [comment]
/override ci/prow/e2e-cmd
this is being rate-limitted by docker.io, I'll work in a followup to pick the appropriate PR into 4.6 which alleviates the problem

**Comment by dmage** [comment]
Can somebody tag it as approved and cherry-pick-approved?

**Comment by xiuwang** [comment]
@wangke19 @xingxingxia Could you help add /label cherry-pick-approved? Thanks

**Pull request merged**
