### PR TITLE
Bug 2032589: Make OriginImageMutators aware of origin objects

### PR DESCRIPTION
**Pull request by dmage**
OriginImageMutators provides the method GetAnnotationAccessor which returns an accessor that should be aware of origin objects. This change makes it provide access to template annotations of deployment configs and other origin objects.

### CODE REVIEW

**Review by ricardomaraschini — APPROVED** [review]

**Comment by xiuwang** [comment]
Validate steps passed https://bugzilla.redhat.com/show_bug.cgi?id=2032589#c3

/lgtm
/label qe-approved

**Pull request merged**
