### PR TITLE
[WIP] Test

### PR DESCRIPTION
**Pull request by dinhxuanvu**

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@coreydaley Hey Corey. Would you mind taking a look at those build tests to see why they are failing? Thanks.

**Comment by coreydaley** [comment]
Actually I am in a different department now, but I think that @adambkaplan might be able to look at it or knows who should.

**Comment by coreydaley** [comment]
Sometimes a good old fashioned retest works if it is just a flake or infrastructure issue also.
/retest

**Comment by p0lyn0mial** [comment]
> Sometimes a good old fashioned retest works if it is just a flake or infrastructure issue also.

It won't the test are failing permanently. The test fail because they are not able to find `ruby-3.0-ubi8` images.
I have just found https://github.com/openshift/origin/pull/29134 this morning and I think it should resolve the issue.

**Comment by dinhxuanvu** [comment]
No longer needed
/close

**Pull request closed without merging**
