### PR TITLE
Bug 1755115: allow scheduled imagestream imports for dockerimages with sha/digest …

### PR DESCRIPTION
**Pull request by gabemontero**
…refs

/assign @bparees 
@smarterclayton 
@dmage 

one more spot ... see https://github.com/openshift/cluster-samples-operator/pull/186#issuecomment-536036652

### CODE REVIEW

**Comment by bparees** [comment]
seems like we're lacking sufficient test coverage of the validation behavior that we didn't catch this in your original PRs.

also can this code be combined w/ the other validation locations?

**Comment by gabemontero** [comment]
> seems like we're lacking sufficient test coverage of the validation behavior that we didn't catch this in your original PRs.

Yep I'll see about adding a unit test

> 
> also can this code be combined w/ the other validation locations?

with the code removals that have occurred, there is only one spot now where we deal with the `Scheduled` field, and it is in `ValidateImageStreamTagReference`

`ValidateImageStreamImport` short circuits at a higher level and does not need to interrogate the `Scheduled` field

**Comment by gabemontero** [comment]
test case added @bparees

**Pull request merged**
