### PR TITLE
Upgrade distribution to v3

### PR DESCRIPTION
**Pull request by flavianmissi**
In https://issues.redhat.com/browse/IR-371 we had to upgrade the registry (and library-go) to use distribution v3. To be on the safe side, we're upgrading distribution to v3 everywhere where is relevant.

### CODE REVIEW

**Comment by flavianmissi** [comment]
`e2e-aws-ovn` failure is caused to the deprecation warning for DeploymentConfigs. Reported it: [OCPBUGS-15291](https://issues.redhat.com/browse/OCPBUGS-15291)

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Comment by dinhxuanvu** [comment]
@p0lyn0mial PTAL for approval

**Comment by ardaguclu** [comment]
unrelated failure;
/retest-required

**Pull request merged**
