### PR TITLE
Bug 1894918: Panic output due to timeouts in openshift-apiserver

### PR DESCRIPTION
**Pull request by p0lyn0mial**

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
requires https://github.com/openshift/kubernetes-apiserver/pull/23

**Comment by knobunc** [comment]
[As patch-manager] Pulling the cherry-pick-approval since the PR didn't make the merge window... sorry. Please resolve the CI problems so it can make next week's window.

**Comment by p0lyn0mial** [comment]
/hold

https://github.com/openshift/openshift-apiserver/pull/164 already contains the changes introduced in this PR.

**Comment by bparees** [comment]
> #164 already contains the changes introduced in this PR.

#164 has been cherry pick approved, can we close this?

**Comment by p0lyn0mial** [comment]
> #164 has been cherry pick approved, can we close this?

/close

**Pull request closed without merging**
