### PR TITLE
Bug 2018442: Image policy should mutate DeploymentConfigs

### PR DESCRIPTION
**Pull request by dmage**
This is a cherry-pick of #250 to address the [bug 2018442](https://bugzilla.redhat.com/show_bug.cgi?id=2018442).

**Impact:** Resolution of image stream names in deployment configs does not work because the image policy plugin does not know about them.

**Cause:** The problem exists since the beginning, but it wasn't visible as the image policy plugin used to resolve image streams names in all pods. Once we've fixed the [bug 1925180](https://bugzilla.redhat.com/show_bug.cgi?id=1925180), the plugin doesn't update controlled objects anymore, i.e. it doesn't update pods that are created for the deployment config.

**Resolution:** Update the admission plugin so that is aware of deployment configs.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by sttts** [comment]
@dmage can you provide the following:

1.  If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
    - [ ] verified
    - [ ] does not apply
2. The bug has significant impact either through severity, reduction in supportability, or number of users affected.
    - [ ] verified
    - [ ] does not apply
3. For branches that are in the Maintenance lifecycle phase:
    - [ ] The bug is a critical fix, no reasonable workaround exists, and a recommendation for upgrade has been ruled out, or 
    - [ ] The bug is a security related bug
    - [ ] Branch not in maintenance mode yet (current release + previous release for 90 days after current GA; everything older is in maintenance)
4. The severity field of the bug must be set to accurately reflect criticality.
    - [ ] verified
5. The PR was created with the cherry-pick bot OR the PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how a user can identify whether a particular cluster is affected.
    - [ ] verified

**Comment by dmage** [comment]
1. If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
   
   * [x]  verified
   * [ ]  does not apply
2. The bug has significant impact either through severity, reduction in supportability, or number of users affected.
   
   * [x]  verified
   * [ ]  does not apply
3. For branches that are in the Maintenance lifecycle phase:
   
   * [x]  The bug is a critical fix, no reasonable workaround exists, and a recommendation for upgrade has been ruled out, or
   * [ ]  The bug is a security related bug
   * [x]  Branch not in maintenance mode yet (current release + previous release for 90 days after current GA; everything older is in maintenance)
4. The severity field of the bug must be set to accurately reflect criticality.
   
   * [x]  verified
5. The PR was created with the cherry-pick bot OR the PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how a user can identify whether a particular cluster is affected.
   
   * [x]  verified

**Pull request merged**
