### PR TITLE
OCPBUGS-27094: UPSTREAM: <carry>: retry etcd Unavailable errors 

### PR DESCRIPTION
**Pull request by p0lyn0mial**
Pulls in https://github.com/openshift/kubernetes/pull/1681 and https://github.com/openshift/kubernetes/pull/1676 via https://github.com/openshift/kubernetes-apiserver/pull/51

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by tkashem** [comment]
/approve

Thanks @p0lyn0mial

**Pull request merged**
