### PR TITLE
[release-4.14]: OCPBUGS-21464: Enable HTTP/2 CVE mitigation

### PR DESCRIPTION
**Pull request by dgrisonnet**

### CODE REVIEW

**Comment by dgrisonnet** [comment]
The test failure is reporting oauth-server disruption, so it should be fine to retry.

/retest

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by dgrisonnet** [comment]
Cherry-pick-approve is for QEs, `backport-risk-assessed` is the one that needs to be set

**Comment by dinhxuanvu** [comment]
> Cherry-pick-approve is for QEs, `backport-risk-assessed` is the one that needs to be set

Oops. Wrong tag :(

**Comment by gangwgr** [comment]
Post merge verification of bug
```
gh pr checkout 397
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 118 (delta 83), reused 113 (delta 83), pack-reused 0
Receiving objects: 100% (118/118), 30.96 KiB | 6.19 MiB/s, done.
Resolving deltas: 100% (83/83), completed with 74 local objects.
From https://github.com/openshift/openshift-apiserver
 * [new ref]             refs/pull/397/head -> OCPBUGS-21464
Switched to branch 'OCPBUGS-21464'
rahulgangwar@rgangwar-mac openshift-apiserver % ls  flags.patch
flags.patch
rahulgangwar@rgangwar-mac openshift-apiserver % git apply flags.patch
make clean; make build
rm -f openshift-apiserver
rm -f ./openshift-apiserver
go build -mod=vendor -trimpath -ldflags "-X github.com/openshift/openshift-apiserver/pkg/version.versionFromGit="v4.0.0-alpha.0-635-gef73f7f" -X github.com/openshift/openshift-apiserver/pkg/version.commitFromGit="ef73f7f7a" -X github.com/openshift/openshift-apiserver/pkg/version.gitTreeState="dirty" -X github.com/openshift/openshift-apiserver/pkg/version.buildDate="2023-11-28T07:18:25Z" " github.com/openshift/openshift-apiserver/cmd/openshift-apiserver

./openshift-apiserver start --help | grep "UnauthenticatedHTTP2DOSMitigation"
                                                                UnauthenticatedHTTP2DOSMitigation=true|false (BETA - default=true)
```

**Pull request merged**
