### PR TITLE
[release-4.15] OCPBUGS-31469: vendor upgrade runtime-utils

### PR DESCRIPTION
**Pull request by QiWang19**
backport fix #419

### CODE REVIEW

**Comment by QiWang19** [comment]
@flavianmissi PTAL

**Comment by flavianmissi** [comment]
we need someone to approve @QiWang19.
/lgtm

**Review by sanchezl — APPROVED** [review]

**Comment by sanchezl** [comment]
This test is consistently failing in the e2e-aws-ovn-cmd job:

[sig-cli][Feature:LegacyCommandTests][Disruptive][Serial] test-cmd: test/cmd/images.sh [apigroup:image.openshift.io]

/hold

**Comment by sanchezl** [comment]
/hold cancel

The test is failing because the fixes in https://github.com/openshift/origin/pull/28675 have not yet been backported.

**Comment by QiWang19** [comment]
@wewang58 could you tag the cherry pick label?

**Comment by wewang58** [comment]
@QiWang19  Seems i have no permission to add cherry-pick-approved label

**Comment by QiWang19** [comment]
@flavianmissi node team QE does not have the power to add the cherrypick label

**Comment by flavianmissi** [comment]
Yeah same is true for image registry QE. That's not what's holding this PR from merging though - it's backport assessment. Let's see if I'm allowed.
/label backport-risk-assessed

**Comment by flavianmissi** [comment]
@sanchezl can you help with `backport-risk-assessed` label as well? Thanks!

**Review by soltysh — APPROVED** [review]
/label backport-risk-assessed

**Pull request merged**
