### PR TITLE
Proof for https://github.com/openshift/kubernetes-apiserver/pull/56

### PR DESCRIPTION
**Pull request by liouk**

### CODE REVIEW

**Comment by chiragkyal** [comment]
Hi @liouk, looks like https://github.com/openshift/openshift-apiserver/pull/407 is hitting Kube 1.29 rebase issue. I see the CIs are mostly green here, can we please move forward with this PR?

**Comment by chiragkyal** [comment]
I've created a follow-up PR https://github.com/openshift/openshift-apiserver/pull/425 to unblock https://github.com/openshift/openshift-apiserver/pull/407

/hold

**Comment by liouk** [comment]
#425 merged, closing
/close

**Pull request closed without merging**
