### PR TITLE
OCPBUGS-501: fix printer panic

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Review by sanchezl — APPROVED** [review]
Looks good, but needs a `make update`. Not sure why the generated openapi schema changed (maybe a new tool version?).

**Comment by tkashem** [comment]
> Looks good, but needs a `make update`. Not sure why the generated openapi schema changed (maybe a new tool version?).

@sanchezl looks like, it's an issue with ci for this repo, i re-ran verify (no code change) and it passed.

**Comment by tkashem** [comment]
the ci jobs in this pr are out of sync for some reason,  closed in favor of https://github.com/openshift/openshift-apiserver/pull/333

**Pull request closed without merging**
