### PR TITLE
OCPBUGS-27104: UPSTREAM: <carry>: retry etcd Unavailable errors

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by tkashem** [comment]
/hold

it's proof pr, once it is green we can merge https://github.com/openshift/kubernetes-apiserver/pull/53

**Comment by tkashem** [comment]
proof pr is green, going to rebase

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by tkashem** [comment]
/hold
until we get green nightly with this fix in master

**Comment by dinhxuanvu** [comment]
CI is green on 4.15 so we can merge this.
/hold cancel

**Comment by p0lyn0mial** [comment]
/retitle OCPBUGS-27151: UPSTREAM: : retry etcd Unavailable errors

**Pull request merged**
