### PR TITLE
Bug 1751258: Using manifest digest on manifest list import

### PR DESCRIPTION
**Pull request by ricardomaraschini**
When importing a manifest list only one manifest is imported therefore
we need to use this one manifest digest instead of the digest for the
whole manifest list when checking for integrity.

### CODE REVIEW

**Comment by dmage** [comment]
@ricardomaraschini as it's a bug fix, it deserves a test

**Comment by ricardomaraschini** [comment]
> @ricardomaraschini as it's a bug fix, it deserves a test

Well, I implemented an unit test to validate a ManifestList import. PTAL.

**Comment by dmage** [comment]
@adambkaplan can you take a look?

**Pull request merged**
