### PR TITLE
IR-113: OCI Schema support for ImageStream import

### PR DESCRIPTION
**Pull request by ricardomaraschini**
OCI Schema support for image stream imports.

### CODE REVIEW

**Comment by dmage** [comment]
/hold

Once we get lgtm and approved on this PR, we'll also need to get approvals from QE, Docs, and Px. Do not unhold until all approvals are granted.

**Comment by ricardomaraschini** [comment]
/assign @wzheng1 @bmcelvee @sferich888

This PR got approval from the engineering team and is ready for next approvals. Please use /label XXX-approved (where XXX is qe, docs, or px) to approve this PR.

@wzheng1 - here we have added support to OCI images during image stream imports.
@bmcelvee @sferich888 - not sure where we should state that we now support OCI image as well.

**Comment by dmage** [comment]
*note:* we don't have XXX-labels on this repo, so just leave a comment whether you approve these changes or not.

**Comment by bmcelvee** [comment]
Since there are note labels on this repo: docs-approved.

I have a few questions about where the documentation will land for this one, aside from release notes, but I will follow up on those questions in Jira. The aligned docs story for reference: [OSDOCS-1590](https://issues.redhat.com/browse/OSDOCS-1590).

**Comment by wzheng1** [comment]
@xiuwang Could you please review?

**Comment by wzheng1** [comment]
QE drafted test case in this sub issue for review, @ricardomaraschini Could you please review?

**Comment by ricardomaraschini** [comment]
/unhold

We already got approvals from qe, docs and px. Unhold so it can get merged.

**Pull request merged**
